highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
  math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: # Required: replace this with your domain
name: estas # Required: will be displayed on every page's header
title: estas # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - 성인자폐(성)당사자 자치 자조모임 
  - APO estas의 공식 홈페이지입니다
description: "성인자폐(성)당사자 자조모임 estas" # Required

disqus:
  comments: false # Global toggle on/off disqus comment
  shortname:  # Required if you use disqus. Replace with your disqus shortname here

gitalk:
  comments: true # Global toggle on/off gitalk comment
  # replace all of those below with your own
  client_id: 9390ead0b81d938cd1ed
  client_secret: 307d8587f0307702c6994483596fd04685f2d364
  repo: jekyll-theme-textalic
  owner: we-estas
  admin: we-estas
  distraction_free_mode: true


google_analytics:
  id: "" # Required if you use google analytics. Replace with your tracking id here

collections: # Define post series here
  demo_series:
    output: true
  demo_series_2:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
